Adds upgrade support for ACLs from 4.7.5 to 5.x
fcrepo-exts/fcrepo-upgrade-utils pull request #29
Opened 2020-11-30 23:46 UTC by dbernstein

Resolves: https://jira.lyrasis.org/browse/FCREPO-2985

**Adds support for upgrading ACLs from 4.7.5 to 5.x**
* * *

**JIRA Ticket**: https://jira.lyrasis.org/browse/FCREPO-2985

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)

# What does this Pull Request do?
On upgrading to 4.7.5, this PR essentially performs the transforms necessary to bring the 4.7.5 acls into alignment with 5.x.
What that means is the following: 
1.  on the protected resource the "acl:accessControl" predicate is removed.
2. the object to which the aforementioned predicate points is imported using the following steps:
     a. Verify that the resource is of type "webac#Acl"
     b. Create new acl in the proper location (under the protected resource at "resource/fcr:acl")
     c. Recurse the child resources of the original ACL and add any authorizations  to the new ACL using hash URIs in the subjects.
 
# How should this be tested?

1.  Run fcrepo 4.7.5.
```
java -jar fcrepo-webapp-4.7.5-jetty-console.jar --headless
```
2. Create a resource and an ACL
```
# create resource
curl -u fedoraAdmin:fedoraAdmin -X PUT http://localhost:8080/rest/container1 --data "" -H "Content-Type: text/turtle"

# create acl
curl -u fedoraAdmin:fedoraAdmin -X PUT http://localhost:8080/rest/acl --data "<> a http://fedora.info/definitions/v4/webac#Acl ." -H "Content-Type: text/turtle"

# attach acl to resource
curl -u fedoraAdmin:fedoraAdmin "http://localhost:8080/rest/container1" -X PATCH -H "Content-Type: application/sparql-update" --data "INSERT DATA { <http://localhost:8080/rest/container1> <http://www.w3.org/ns/auth/acl#accessControl> <http://localhost:8080/rest/acl>. }"

```
3. Create two authorizations
auth0.ttl
```
@prefix acl: <http://www.w3.org/ns/auth/acl#>.

<> a acl:Authorization;
   acl:accessTo </fcrepo/rest/container1>;
   acl:agent "testuser";
   acl:mode acl:Read.
```
PUT it.
```
curl -u fedoraAdmin:fedoraAdmin -X PUT http://localhost:8080/rest/acl/auth0 --data "@auth0.ttl"
```

auth1.ttl
```
@prefix acl: <http://www.w3.org/ns/auth/acl#>.

<> a acl:Authorization;
   acl:accessTo </fcrepo/rest/container1>;
   acl:agent "testuser";
   acl:mode acl:Read.
```
PUT it:
```
curl -u fedoraAdmin:fedoraAdmin -X PUT http://localhost:8080/rest/acl/auth1 --data "@auth1.ttl"
```

5. Perform an export using fcrepo-import-export-0.3.0
```
java -jar fcrepo-import-export-0.3.0.jar -b -d 4.7.5-export -u fedoraAdmin:fedoraAdmin  -m export -r http://localhost:8080/rest  
```
6. Upgrade from 4.7.5 to 5.x
```
java -Dfcrepo.log=DEBUG -jar ~/code/fcrepo-upgrade-utils/target/fcrepo-upgrade-utils-6.0.0-SNAPSHOT.jar -i 4.7.5-export -o 5.1.1-export  -s 4.7.5 -t 5+ -u  http://localhost:8080/rest
```

7. Upgrade from 5.x to 6.
```
java -Dfcrepo.log=DEBUG -jar fcrepo-upgrade-utils-6.0.0-SNAPSHOT.jar -i 5.1.1-export  -o fcrepo-6-home/data -s 5+ -t 6+ -u http://localhost:8080/rest
```
8. Stop Fedora 4.7.5 
9. Start Fedora 6.0.0
```
java -Dfcrepo-home=fcrepo-6-home -jar fcrepo-webapp-6.0.0-SNAPSHOT-jetty-console.jar --headless
```

10. Verify that the ACL has been migrated and the old ACL and Authorizations no longer exist: 
```
# expect 404s:
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/acl
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/acl/auth0
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/acl/auth1

# expect 202
curl -u fedoraAdmin:fedoraAdmin http://localhost:8080/rest/container1/fcr:acl

# validate that the acls have been merged (you should see hash uris  with the following subjects: 
http://localhost:8080/rest/container1/fcr:acl#auth0
http://localhost:8080/rest/container1/fcr:acl#auth1
```

# Interested parties
Tag (@ mention) interested parties or, if unsure, @fcrepo/committers

2020-12-01 22:41 UTC, awoods requested changes

2020-12-01 22:41 UTC, awoods commented on src/main/java/org/fcrepo/upgrade/utils/F47ToF5UpgradeManager.java
> +        final var allowablePredicates = Arrays.asList(RDF.type, FEDORA_CREATED_DATE, FEDORA_LAST_MODIFIED_DATE, FEDORA_CREATED_BY, FEDORA_LAST_MODIFIED_BY);
Please limit the line length here to 120 characters.

2020-12-01 22:41 UTC, awoods commented on src/main/java/org/fcrepo/upgrade/utils/F47ToF5UpgradeManager.java
> +                aclTriples.add(aclModel.createStatement(newAclResource, x.getPredicate(), x.getObject()));
May as well use the variables created above:
- `predicate` instead of `x.getPredicate()`
- `obj` instead of `x.getObject()`

2020-12-01 22:41 UTC, awoods commented on src/main/java/org/fcrepo/upgrade/utils/F47ToF5UpgradeManager.java
> +    private String removeExtension(String path) {
Probably less fragile to use [FilenameUtils](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FilenameUtils.html#removeExtension-java.lang.String-).

2020-12-01 22:41 UTC, awoods commented on src/main/java/org/fcrepo/upgrade/utils/F47ToF5UpgradeManager.java
> +        return createResource(resource.getURI()
May as well fix the formatting here.

2020-12-01 22:41 UTC, awoods commented on src/main/java/org/fcrepo/upgrade/utils/RdfConstants.java
> +    public static final Resource LDP_CONTAINS = ResourceFactory.createResource(LDP_NS + "contains");
Can remove... unused.

2020-12-01 22:41 UTC, awoods commented on src/main/java/org/fcrepo/upgrade/utils/RdfConstants.java
> +    public static final Property FEDORA_WEB_ACL =
Can remove... unused.

2020-12-01 22:41 UTC, awoods commented on src/test/java/org/fcrepo/upgrade/utils/F47ToF5UpgradeManagerTest.java
> +        final var model = RdfUtil.parseRdf(Path.of(output.toString(), "rest/container1/fcr%3Aacl.ttl"), Lang.TTL);
Please limit line length to 120 characters.

2020-12-01 22:41 UTC, awoods commented on src/test/java/org/fcrepo/upgrade/utils/F47ToF5UpgradeManagerTest.java
> +                                               .filter(x -> x.getPredicate().equals(FEDORA_LAST_MODIFIED_DATE)).findFirst().get();
Please limit line length to 120 characters.

2020-12-01 23:02 UTC, awoods commented
Thank you for the detailed test instructions. That is great.
I had to make a couple of changes:
- Step no-2: `# create acl` needs the minor update or adding angle-brackets as below:
   ```
   <http://fedora.info/definitions/v4/webac#Acl>
   ```
- Step no-3: Need to create the "auth0.ttl" and "auth1.ttl" as containers, not binaries... by adding to the PUT requests:
   ```
   -H"Content-type: text/turtle"
   ```

Everything works fine until I get to step no-6, which results in the following error:
```
DEBUG 17:57:28.183 (F47ToF5UpgradeManager) copy file ../4.7.5-export/rest/container1.ttl to ../5.1.1-export/rest/container1.ttl
java.lang.RuntimeException: java.io.FileNotFoundException: ../5.1.1-export/rest/container1/fcr%3Aacl.ttl (No such file or directory)
	at org.fcrepo.upgrade.utils.F47ToF5UpgradeManager.convertAcl(F47ToF5UpgradeManager.java:396)
	at org.fcrepo.upgrade.utils.F47ToF5UpgradeManager.lambda$upgradeRdfAndCreateHeaders$5(F47ToF5UpgradeManager.java:270)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.fcrepo.upgrade.utils.F47ToF5UpgradeManager.upgradeRdfAndCreateHeaders(F47ToF5UpgradeManager.java:208)
	at org.fcrepo.upgrade.utils.F47ToF5UpgradeManager.processFile(F47ToF5UpgradeManager.java:157)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.fcrepo.upgrade.utils.F47ToF5UpgradeManager.processDirectory(F47ToF5UpgradeManager.java:122)
	at org.fcrepo.upgrade.utils.F47ToF5UpgradeManager.start(F47ToF5UpgradeManager.java:116)
	at org.fcrepo.upgrade.utils.UpgradeUtilDriver.run(UpgradeUtilDriver.java:84)
	at org.fcrepo.upgrade.utils.UpgradeUtilDriver.main(UpgradeUtilDriver.java:69)
Caused by: java.io.FileNotFoundException: ../5.1.1-export/rest/container1/fcr%3Aacl.ttl (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.fcrepo.upgrade.utils.F47ToF5UpgradeManager.convertAcl(F47ToF5UpgradeManager.java:393)
```

2020-12-02 21:56 UTC, dbernstein commented
Let me take a look.

2020-12-02 22:39 UTC, dbernstein commented
@awoods :  I wasn't able to reproduce the problem, but I suspect it has to do with some minor differences in the way files are handled by osx vs linux.   I've added an [explicit mkdirs](https://github.com/fcrepo-exts/fcrepo-upgrade-utils/pull/29/files#diff-260dec6d546279fcb918ba4955b07083608b82d30fb96092173309753bcd7131R350) on the new ACL file which I _believe_ should solve the problem you're seeing.

2020-12-03 00:18 UTC, awoods approved these changes

2020-12-03 00:19 UTC, merged