Update jackson
fcrepo-exts/fcrepo-upgrade-utils pull request #39
Opened 2021-06-14 18:28 UTC by mikejritter

# What does this Pull Request do?

Updates the version of jackson to match `fcrepo-storage-ocfl`. When they fell out of sync tests were failing when running `mvn verify`. 

# How should this be tested?

Run `mvn clean verify` and see all tests pass.

# Interested parties

@fcrepo/committers

2021-06-15 19:32 UTC, dbernstein requested changes
@mikejritter : can you update the snapshot repository url to use http.  The build appears to be broken due to that.

2021-06-15 23:29 UTC, dbernstein approved these changes

2021-06-16 15:16 UTC, dbernstein commented
@mikejritter : It looks like there's a problem with the tests on windows now.

2021-06-18 17:09 UTC, dbernstein approved these changes

2021-06-18 17:22 UTC, pwinckles approved these changes

2021-06-18 17:22 UTC, merged